version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finako_backend
    ports:
      - "8000:8000"
    volumes:
      # Mount environment variables
      - ./backend/.env:/app/.env
    restart: unless-stopped
    networks:
      - finako_net

  n8n:
    image: n8nio/n8n:latest
    container_name: finako_n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Jakarta
      - TZ=Asia/Jakarta
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - finako_net

volumes:
  n8n_data:

networks:
  finako_net:
    driver: bridge
